[zsh]
#pre = "python docker vim"
theme = "powerlevel10k"
apt = "zsh highlight neofetch tldr tree"
pip = "pygments"

[zsh.plugins]
cd-ls = true
F-Sy-H = true
zsh-vi-mode = true
zsh-autosuggestions = true
zsh-interactive-cd = true
git = true
docker = true
pyenv = true
wakeonlan = true
web-search = true
colored-man-pages = true

[zsh.aliases]
hcat = "highlight -O ansi --force"
pcat = "pygmentize -g -O style=colorful,linenos=1"
sman = "tldr"
apple = "neofetch -s"

